version: 2 
jobs: 
  install-dependencies: 
    working_directory: ~/circle-ci-js-example 
    docker: 
      - image: circleci/node:10 
    steps:
      - checkout 
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  lint: 
    working_directory: ~/circle-ci-js-example 
    docker: 
      - image: circleci/node:10 
    steps:
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: lint
          command: npm run lint
  format-check: 
    working_directory: ~/circle-ci-js-example 
    docker: 
      - image: circleci/node:10 
    steps:
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: format:check
          command: npm run format:check
  test: 
    working_directory: ~/circle-ci-js-example 
    docker: 
      - image: circleci/node:10 
    steps:
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: test
          command: npm run test

workflows:
  version: 2

  js-example-workflow:
    jobs:
      - install-dependencies:
          filters:
            tags:
              only: /.*/
      - format-check:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - install-dependencies
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - format-check
            - lint
          filters:
            tags:
              only: /.*/